name: CI

on:
  push:
    branches:
      - master
      - setup-ci
    tags:
      - '**'
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests

    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11'
      
      - name: Install deps
        run: |
          pip install uv
          uv venv
          . .venv/bin/activate
          uv --version
          uv pip install -r dev-requirements.txt

      - name: Run tests
        run: |
          . .venv/bin/activate
          pytest --cov=volley_grids --cov-report=xml --cov-report=term-missing --cov-report=html --cov-append
      
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ./htmlcov

  ruff-check:
    name: ruff
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install deps
      run: |
          pip install ruff

    - name: run ruff check
      run: ruff check
