name: CI

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    name: test ${{ matrix.os }} / ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.8
      
      - name: Install deps
        run: |
          sudo apt-get update && sudo apt-get -y install uv
          uv venv
          . venv/bin/activate
          uv pip install -e .[dev]

      - name: Run tests
        run: |
          pytest --cov=volley_grids --cov-report=xml --cov-report=term-missing --cov-report=html --cov-append
      
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

  ruff-check:
    name: ruff
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install deps
      run: |
          sudo apt-get update && sudo apt-get -y install uv ruff
          uv venv
          . venv/bin/activate
          uv pip install -e .[dev]

    - name: run ruff check
      run: ruff check
